ktor {
    deployment {
        port = 8083
    }
    application {
        modules = [ com.moodavatar.avatar.ApplicationKt.module ]
    }
}

jwt {
    secret   = ${JWT_SECRET}
    issuer   = ${JWT_ISSUER}
    audience = ${JWT_AUDIENCE}
}

mongodb {
    uri  = ${MONGO_URI}
    db   = ${MONGO_DB}
}
