ktor {
    deployment {
        port = 8082
    }
    application {
        modules = [ com.moodavatar.user.ApplicationKt.module ]
    }
}

jwt {
    secret = ${JWT_SECRET}
    issuer = ${JWT_ISSUER}
    audience = ${JWT_AUDIENCE}
}

database {
    host = ${DB_HOST}
    port = ${DB_PORT}
    name = ${DB_NAME}
    user = ${DB_USER}
    password = ${DB_PASSWORD}
}

services {
    authUrl = ${AUTH_SERVICE_URL}
}

rabbitmq {
    host     = "rabbitmq"
    host     = ${?RABBITMQ_HOST}
    port     = 5672
    port     = ${?RABBITMQ_PORT}
    user     = "guest"
    user     = ${?RABBITMQ_USER}
    password = "guest"
    password = ${?RABBITMQ_PASSWORD}
}
